---

# ------------------------------------------------------------------------------
#   ==========================================================================
#                                    NOTE:
#                                   SECRETS!
#                               Don't check in?
#   ==========================================================================
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# Network Drives
# ------------------------------------------------------------------------------

nfs:
  mounts:
    - type: cifs
      # source: //home-2017-desk.local/media
      source: //192.168.50.20/media
      directory: /mnt/nfs/media
      options: "uid=main,gid=main,user=media-share,password=6W>^%K9@C-.sfVs!o7Hyzh6*8bHMm6,iocharset=utf8"
    - type: cifs
      # source: //home-2017-desk.local/bree
      source: //192.168.50.20/bree
      directory: /mnt/nfs/bree
      options: "ro,uid=main,gid=main,user=media-share,password=6W>^%K9@C-.sfVs!o7Hyzh6*8bHMm6,iocharset=utf8"


# ------------------------------------------------------------------------------
# Nomad
# ------------------------------------------------------------------------------

nomad:
  root: /srv/nomad
  data: /srv/nomad/data
  host_volumes:
    - name: files-temp
      directory: /tmp
      read_only: false
      # Should already exist. Just make sure it does.
      create: false
    - name: files-media
      directory: /mnt/nfs/media
      read_only: false
      # Should already exist. Just make sure it does.
      create: false
    - name: files-bree
      directory: /mnt/nfs/bree
      read_only: false
      # Should already exist. Just make sure it does.
      create: false
    - name: pihole-data
      directory: /srv/nomad/pihole/etc/pihole
      read_only: false
      create: true
      owner: root
      group: root
    - name: pihole-dnsmasq
      directory: /srv/nomad/pihole/etc/dnsmasq.d
      read_only: false
      create: true
      owner: root
      group: root
    - name: pihole-backups
      directory: /srv/nomad/pihole/backups
      read_only: false
      create: true
      owner: root
      group: root
    - name: plex-config
      directory: /srv/nomad/plex/config
      read_only: false
      create: true
      owner: nomad
      group: nomad
    - name: jackett-config
      directory: /srv/nomad/jackett/config
      read_only: false
      create: true
      owner: nomad
      group: nomad
    - name: qbittorrent-config
      directory: /srv/nomad/qbittorrent/config
      read_only: false
      create: true
      owner: nomad
      group: nomad
    # - name: tailscale-data
    #   directory: /srv/nomad/tailscale/data
    #   read_only: false
    #   create: true
    #   owner: nomad
    #   group: nomad
    # - name: jellyfin-config
    #   directory: /srv/nomad/jellyfin/config
    #   read_only: false
    #   create: true
    #   owner: jellyfin
    #   group: jellyfin


# ------------------------------------------------------------------------------
# Nomad Job: Pi-Hole
# ------------------------------------------------------------------------------

pihole:
  # ----------------------------------------------------------------------------
  # Whitelists (domains & regexes)
  # ----------------------------------------------------------------------------
  # Most of these are from:
  #   https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212
  whitelist:
    # ------------------------------
    # Whitelist, Domains
    # ------------------------------
    # More than one domain is allowed per entry; separate with spaces.
    domains:
      # --------------------------------------------------------------------------
      # Apple
      # --------------------------------------------------------------------------
      # Apple ID
      - appleid.apple.com
      # iOS Weather app
      - gsp-ssl.ls.apple.com gsp-ssl.ls-apple.com.akadns.net
      # Apple Music
      - itunes.apple.com
      - s.mzstatic.com

      #---------------------------------------------------------------------------
      # Phones
      #---------------------------------------------------------------------------
      # ------------------------------
      # Android
      # ------------------------------

      # Google Play
      - android.clients.google.com

      # ------------------------------
      # "Captive-Portal" / Internet Connectivity tests
      # ------------------------------

      # Android/Chrome
      - connectivitycheck.android.com android.clients.google.com clients3.google.com connectivitycheck.gstatic.com

      # Windows/Microsoft
      - msftncsi.com www.msftncsi.com ipv6.msftncsi.com

      # iOS/Apple
      - captive.apple.com gsp1.apple.com www.apple.com www.appleiphonecell.com

      #---------------------------------------------------------------------------
      # OS / Apps
      #---------------------------------------------------------------------------

      # Microsoft BitLocker
      - g.live.com

      # Android OS Updates?
      - appspot-preview.l.google.com

      # Windows 10 updates
      - sls.update.microsoft.com.akadns.net fe3.delivery.dsp.mp.microsoft.com.nsatc.net tlu.dl.delivery.mp.microsoft.com

      # Microsoft Edge Updates
      - msedge.api.cdp.microsoft.com

      # NVIDIA GeForce Experience
      - gfwsl.geforce.com

      # Android TV
      - redirector.gvt1.com

      # Gmail (iOS app won't connect without this?)
      - googleapis.l.google.com

      # YouTube Apps
      - www.googleapis.com
      - youtubei.googleapis.com
      - oauthaccountmanager.googleapis.com

      # Microsoft Store
      - dl.delivery.mp.microsoft.com geo-prod.do.dsp.mp.microsoft.com displaycatalog.mp.microsoft.com

      # Edge Browser Updates
      - msedge.api.cdp.microsoft.com

      # Microsoft Office
      - officeclient.microsoft.com

      # Google Chrome (on Ubuntu?)
      - dl.google.com

      # Google Keep (notes app)
      - reminders-pa.googleapis.com firestore.googleapis.com

      # Spotify
      - spclient.wg.spotify.com apresolve.spotify.com

      # Spotify on TVs
      - api-tv.spotify.com

      # Plex Domains
      - plex.tv tvdb2.plex.tv pubsub.plex.bz proxy.plex.bz proxy02.pop.ord.plex.bz cpms.spop10.ams.plex.bz meta-db-worker02.pop.ric.plex.bz meta.plex.bz tvthemes.plexapp.com.cdn.cloudflare.net tvthemes.plexapp.com 106c06cd218b007d-b1e8a1331f68446599e96a4b46a050f5.ams.plex.services meta.plex.tv cpms35.spop10.ams.plex.bz proxy.plex.tv metrics.plex.tv pubsub.plex.tv status.plex.tv www.plex.tv node.plexapp.com nine.plugins.plexapp.com staging.plex.tv app.plex.tv o1.email.plex.tv  o2.sg0.plex.tv dashboard.plex.tv

      # Domains used by Plex
      - gravatar.com # custom login pictures
      - thetvdb.com # metadata for tv series
      - themoviedb.com # metadata for movies
      - chtbl.com # iHeart radio/Plex Podcast

      # Sonarr (Torrent-type thing)
      - services.sonarr.tv skyhook.sonarr.tv download.sonarr.tv apt.sonarr.tv forums.sonarr.tv

      # Dropbox
      - dl.dropboxusercontent.com ns1.dropbox.com ns2.dropbox.com

      # Firefox Tracking Protection
      # May or may not be blocked due to over-eager "tracking" regexes.
      - tracking-protection.cdn.mozilla.net

      # # WhatsApp
      # - wa.me
      # - www.wa.me

      # Signal
      - ud-chat.signal.org chat.signal.org storage.signal.org signal.org www.signal.org updates2.signal.org textsecure-service-whispersystems.org giphy-proxy-production.whispersystems.org cdn.signal.org whispersystems-textsecure-attachments.s3-accelerate.amazonaws.com d83eunklitikj.cloudfront.net souqcdn.com cms.souqcdn.com api.directory.signal.org contentproxy.signal.org turn1.whispersystems.org

      # --------------------------------------------------------------------------
      # Websites
      # --------------------------------------------------------------------------

      # Google Fonts
      - gstaticadssl.l.google.com

      # Google Maps
      - clients4.google.com
      - clients2.google.com

      # Bing Maps
      - dev.virtualearth.net ecn.dev.virtualearth.net t0.ssl.ak.dynamic.tiles.virtualearth.net t0.ssl.ak.tiles.virtualearth.net

      # Microsoft Web Pages
      - outlook.office365.com products.office.com c.s-microsoft.com i.s-microsoft.com login.live.com login.microsoftonline.com

      # YouTube History
      - s.youtube.com
      - video-stats.l.google.com

      # website placeholder images
      - placehold.it placeholdit.imgix.net

      # Lowes "Secure Checkout"
      - assets.adobedtm.com

      # Home Depot "Secure Checkout"
      - nexus.ensighten.com

      # Reddit
      - styles.redditmedia.com www.redditstatic.com reddit.map.fastly.net www.redditmedia.com reddit-uploaded-media.s3-accelerate.amazonaws.com

      # Twitter
      - twitter.com
      - upload.twitter.com
      - api.twitter.com
      - mobile.twitter.com

      #---------------------------------------------------------------------------
      # Gaming
      #---------------------------------------------------------------------------

      # Grand Theft Auto V
      - prod.telemetry.ros.rockstargames.com

      # ------------------------------
      # Xbox
      # ------------------------------

      # Xbox OS Update?
      - assets1.xboxlive.com

      # Xbox Live
      - clientconfig.passport.net

      # Xbox Live Achievements
      - v10.events.data.microsoft.com
      - v20.events.data.microsoft.com

      # Xbox Live Messaging
      - client-s.gateway.messenger.live.com

      # Store App on Series X/S
      - arc.msn.com

      # EA Play on Xbox
      - activity.windows.com

      # "Full Functionality" (IDK)
      - xbox.ipv6.microsoft.com device.auth.xboxlive.com www.msftncsi.com title.mgt.xboxlive.com xsts.auth.xboxlive.com title.auth.xboxlive.com ctldl.windowsupdate.com attestation.xboxlive.com xboxexperiencesprod.experimentation.xboxlive.com xflight.xboxlive.com cert.mgt.xboxlive.com xkms.xboxlive.com def-vef.xboxlive.com notify.xboxlive.com help.ui.xboxlive.com licensing.xboxlive.com eds.xboxlive.com www.xboxlive.com v10.vortex-win.data.microsoft.com settings-win.data.microsoft.com

      # ------------------------------
      # PC Master Race
      # ------------------------------

      # Epic Games (required to log in to Epic Launcher, required to make purchases on their website?)
      - tracking.epicgames.com

      # Origin (save game sync)
      - cloudsync-prod.s3.amazonaws.com

      # ------------------------------
      # PlayStation
      # ------------------------------
      # PS5 "Recently Played" and Trophies
      - telemetry-console.api.playstation.com


    # ------------------------------
    # Whitelist, Regex
    # ------------------------------
    # Only one regular expression allowed per entry!
    regexes:
      #---------------------------------------------------------------------------
      # OS / Apps
      #---------------------------------------------------------------------------

      # # WhatsApp
      # - '^whatsapp-cdn-shv-[0-9]{2}-[a-z]{3}[0-9]\.fbcdn\.net$'
      # - '^((www|(w[0-9]\.)?web|media((-[a-z]{3}|\.[a-z]{4})[0-9]{1,2}-[0-9](\.|-)(cdn|fna))?)\.)?whatsapp\.(com|net)$'

      # --------------------------------------------------------------------------
      # Websites
      # --------------------------------------------------------------------------

      # Reddit
      - '[a-z]\.thumbs\.redditmedia\.com'
      - '(\.|^)redd\.it$'
      - '(\.|^)reddit\.com$'

      # Twitter
      - '(\.|^)twimg\.com$'

  # ----------------------------------------------------------------------------
  # Blacklists (domains & regexes)
  # ----------------------------------------------------------------------------
  blacklist:
    # ------------------------------
    # Blacklist, Domains
    # ------------------------------
    # More than one domain is allowed per entry; separate with spaces.
    domains:
      # ------------------------------------------------------------------------
      # TV
      # ------------------------------------------------------------------------

      # ------------------------------
      # Ads: Android TV Launcher
      #   (Shield TV, maybe Fire TV)
      # ------------------------------
      # https://www.reddit.com/r/ShieldAndroidTV/comments/sjv7ry/comment/hvjcv9b/
      - androidtvwatsonfe-pa.googleapis.com

      # ------------------------------
      # Ads: Samsung TV
      # ------------------------------
      # https://www.reddit.com/r/YouShouldKnow/comments/gn7fw5/ysk_if_you_own_a_samsung_smart_tv_that_has_ads/
      - ads.samsung.com
      - samsungads.com

      # ------------------------------
      # Ads: LG TV
      # ------------------------------
      # # https://www.reddit.com/r/YouShouldKnow/comments/gn7fw5/ysk_if_you_own_a_samsung_smart_tv_that_has_ads/
      - ngfts.lge.com
      - us.ad.lgsmartad.com
      - lgad.cjpowercast.com
      - edgesuite.net
      - us.info.lgsmartad.com

    # ------------------------------
    # Whitelist, Regex
    # ------------------------------
    # Only one regular expression allowed per entry!
    regexes: [ ]

