---



dc_2021_home:
  hosts:
    home_2019_raspi4:
      ansible_become: true
      ansible_host: "192.168.50.16"
      ansible_user: "main"
      # ------------------------------
      # NOTE: Any of these settings could be overridden by
      # "./host_vars/home_2019_raspi4.yaml"
      # ------------------------------
      os:
        user: main
        group: main
      nomad:
        root: /srv/nomad
        data: /srv/nomad/data
        # Each host_volume dict must have:
        #   - name: string
        #   - path: string
        #   - read_only: bool
        host_volumes: []
        # `host_volumes` examples:
        #   - name: files-temp
        #     path: /tmp
        #     read_only: false
        #     # Should already exist. Just make sure it does.
        #     create: false
        #   - name: pihole-dnsmasq
        #     path: /srv/nomad/pihole/etc/dnsmasq.d
        #     read_only: false
        #     # Create if it doesn't exist.
        #     create: true
        #     owner: root
        #     group: root

      backup:
        # This is on localhost.
        root: "/mnt/nfs/media/backup/{{ '%Y-%m-%d' | strftime }}"
      # Speed up playbook testing...
      run:
        install:
          docker: no
          nomad: no
          consul: no
          cifs: no
        apt:
          repo: no
          upgrade: no
          clean: no
        backup:
          clean: yes
        config:
          docker: no
          nomad: no
          consul: no
          cifs: no
        nomad:
          pihole: no
          jackett: no
          qbittorrent: no
          plex: yes
