---

dc_2021_home:
  hosts:
    home_2019_raspi4:
      ansible_become: true
      ansible_host: "192.168.50.16"
      ansible_user: "main"
      os:
        user: main
        group: main
      nomad:
        root: /srv/nomad
        data: /srv/nomad/data
      # Speed up playbook testing...
      run:
        install:
          docker: no
          nomad: no
          consul: no
          cifs: no
        apt_repo: no
        apt_upgrade: no
        apt_clean_up: no
        config:
          docker: no
          nomad: no
          consul: no
          cifs: no
        nomad:
          pihole: no
