---

# ------------------------------------------------------------------------------
# Ensure a Nomad Host Volume exists.
# ------------------------------------------------------------------------------

- name: Nomad Host Volume | {{ host_volume.directory }} | Stat
  stat:
    path: "{{ host_volume.directory }}"
  register: host_volume_dir

# ------------------------------
# Don't create?
# ------------------------------
# Just fail if we shouldn't create the directory and it doesn't exist.
- name: Nomad Host Volume | {{ host_volume.directory }} | Assert Exists
  fail:
    msg: "Nomad Host Volume '{{ host_volume.directory }}' does not exist!"
  when:
    - not host_volume.create
    - not host_volume_dir.stat.exists

# ------------------------------
# Create if necessary.
# ------------------------------
- name: NFS | Mount Directory | {{ host_volume.directory }} | Mount
  file:
    state: directory
    path: "{{ host_volume.directory }}"
    owner: "{{ host_volume.owner }}"
    group: "{{ host_volume.group }}"
    # Defaults to not recursing into directory.
    # Could adjust if we need to mess with permissions of children.
    # recurse: no
  when:
    - host_volume.create
