---

# Host patterns: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
# `&` is for an intersection of groups/hosts.
- hosts: dc_2021_home:&home_2019_raspi4

  # # ============================================================================
  # # Constants
  # # ============================================================================
  # vars:
  #   foo: "bar"

  # # ============================================================================
  # # Execute the roles.
  # # ============================================================================
  # roles:
  #   - harden.linux
  #   - harden.sshd
  #   - harden.ufw

  # ============================================================================
  # Tasks:
  # ============================================================================
  tasks:
    - name: Print | Facts
      ansible.builtin.debug:
        var: ansible_facts

