---

# Host patterns: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
# `&` is for an intersection of groups/hosts.
- hosts: dc_2021_home:&home_2019_raspi4

  # # ============================================================================
  # # Constants
  # # ============================================================================
  # vars:
  #   foo: "bar"

  # # ============================================================================
  # # Execute the roles.
  # # ============================================================================
  # roles:
  #   - foo.bar
  #   - foo.qux
  #   - narf

  # ============================================================================
  # Tasks:
  # ============================================================================
  tasks:
    # # --------------------------------------------------------------------------
    # # Debug
    # # --------------------------------------------------------------------------
    #
    # - name: Print | Facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    #
    # - name: Print | Vars | Host
    #   ansible.builtin.debug:
    #     var: hostvars["home_2019_raspi4"]
    #
    # - name: Print | Vars | Group
    #   ansible.builtin.debug:
    #     var: groups


    # --------------------------------------------------------------------------
    # [Set-Up] Gather Facts
    # --------------------------------------------------------------------------
    - name: Git Root | Gather Fact
      delegate_to: localhost
      command:
        cmd: "git rev-parse --show-toplevel"
      register: cmd_git_root
      changed_when: false

    - name: Git Root | Set Fact
      set_fact:
        path_git_root: "{{ cmd_git_root.stdout }}"


    # --------------------------------------------------------------------------
    # [Install] Apt Repos
    # --------------------------------------------------------------------------
    # Add all extra apt repos before we run apt update/upgarde.

    - name: Apt | HashiCorp Repo
      include_tasks: "apt.add-repo.yaml"
      vars:
        repo_item:
          name_display: HashiCorp
          repo:
            # For repos added like: `deb [{{ architecture }}] URL {{ distribution_release }} BRANCH`
            url: https://apt.releases.hashicorp.com/
            branch: main
          key:
            url: https://apt.releases.hashicorp.com/gpg
            basename: hashicorp # hashicorp.asc, hashicorp.gpg
            checksum:
              # gpg --dearmor < /path/to/repo/ansible/gpg/hashicorp.asc | sha1sum
              # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
              # `ansible.builtin.copy` uses `sha1` for checksumming.
              dearmored: "dcece7980f1a183b1d59b26354247a29057786e0"


    # --------------------------------------------------------------------------
    # [Install] Apt Prep.
    # --------------------------------------------------------------------------
    # Update the apt cache and upgrade existing packages.

    - name: Apt | Update Cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      # Don't care if this says the cache was old - only care if that causes other
      # steps to do something. So the status of this isn't as important - those
      # other steps will say if they changed.
      changed_when: false

    - name: Apt | Upgrade
      apt:
        upgrade: yes


    # --------------------------------------------------------------------------
    # [Install] HashiCorp Stuff: Nomad
    # --------------------------------------------------------------------------

    - name: Apt | Install | HashiCorp Nomad
      apt:
        name: nomad
        state: present # Just need something installed.
        # state: latest # Make sure latest version is installed.

    # TODO: Rest of the Nomad set-up / install?
    #   - Or does that come later?


    # --------------------------------------------------------------------------
    # [Install] HashiCorp Stuff: Consul
    # --------------------------------------------------------------------------

    - name: Apt | Install | HashiCorp Consul
      apt:
        name: consul
        state: present # Just need something installed.
        # state: latest # Make sure latest version is installed.

    # TODO: Rest of the Consul set-up / install?
    #   - Or does that come later?


    # --------------------------------------------------------------------------
    # [Install] Network File Share
    # --------------------------------------------------------------------------

    - name: Apt | Install | CIFS Utils (for NFS)
      apt:
        name: cifs-utils
        state: present


    # --------------------------------------------------------------------------
    # [Mount] Network File Share
    # --------------------------------------------------------------------------

    - name: NFS | Root Directory | Create
      file:
        state: directory
        path: "/mnt/nfs"
        owner: "{{ os.user }}"
        group: "{{ os.group }}"
        recurse: no

    - name: NFS | Mount Directory
      include_tasks: "nfs.add-mount.yaml"
      with_items: "{{ nfs.mounts }}"
      loop_control:
        loop_var: mount_item


    # --------------------------------------------------------------------------
    # [Clean-Up]
    # --------------------------------------------------------------------------

    - name: Apt | Auto-Clean
      apt:
        autoclean: yes

    - name: Apt | Auto-Remove
      apt:
        autoremove: yes


  # # ==============================================================================
  # # Handlers
  # # ==============================================================================
  # handlers:
  #   # Restart `foo` service to pick up new config settings.
  #   - name: restart-service-foo
  #     service:
  #       name: foo
  #       state: restarted
