---

# Host patterns: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
# `&` is for an intersection of groups/hosts.
- hosts: dc_2021_home:&home_2019_raspi4

  # # ============================================================================
  # # Constants
  # # ============================================================================
  # vars:
  #   foo: "bar"

  # # ============================================================================
  # # Execute the roles.
  # # ============================================================================
  # roles:
  #   - foo.bar
  #   - foo.qux
  #   - narf

  # ============================================================================
  # Tasks:
  # ============================================================================
  tasks:
    # --------------------------------------------------------------------------
    # Debug / Test
    # --------------------------------------------------------------------------

    # - name: Print | Facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    #
    # - name: Print | Vars | Host
    #   ansible.builtin.debug:
    #     var: hostvars["home_2019_raspi4"]
    #
    # - name: Print | Vars | Group
    #   ansible.builtin.debug:
    #     var: groups

    - name: Local Fact | Gather | User
      delegate_to: localhost
      command:
        cmd: "whoami"
      register: cmd_whoami
      changed_when: false

    - name: Local Fact | Set | User
      set_fact:
        user_local: "{{ cmd_whoami.stdout }}"

    - name: Local Fact | Gather | Group
      delegate_to: localhost
      command:
        cmd: "getent group {{ user_local }}"
      register: cmd_getent
      changed_when: false

    - name: Local Fact | Set | Group
      set_fact:
        group_local: "{{ cmd_getent.stdout.split(':')[0] }}"

    - name: Print | Local User
      ansible.builtin.debug:
        var: user_local

    - name: Print | Local Group
      ansible.builtin.debug:
        var: group_local
