---

# Host patterns: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
# `&` is for an intersection of groups/hosts.
- hosts: dc_2021_home:&home_2019_raspi4

  # # ============================================================================
  # # Constants
  # # ============================================================================
  # vars:
  #   foo: "bar"

  # # ============================================================================
  # # Execute the roles.
  # # ============================================================================
  # roles:
  #   - foo.bar
  #   - foo.qux
  #   - narf

  # ============================================================================
  # Tasks:
  # ============================================================================
  tasks:
    # --------------------------------------------------------------------------
    # Debug / Test
    # --------------------------------------------------------------------------

    # - name: Print | Facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    #
    # - name: Print | Vars | Host
    #   ansible.builtin.debug:
    #     var: hostvars["home_2019_raspi4"]
    #
    # - name: Print | Vars | Group
    #   ansible.builtin.debug:
    #     var: groups

