version: 2
ethernets:
  eth0:
    dhcp4: false
    addresses: [192.168.254.16/24]
    gateway4: 192.168.254.254
    # TODO: IPv6 Network Stuff?
    # CloudFlare (1.1.1.1 + 1.0.0.1) + Google (8.8.8.8 + 8.8.4.4)
    nameservers:
      addresses: ["1.1.1.1", "8.8.8.8", "1.0.0.1", "8.8.4.4"]


# Local Variables:
# mode: yaml
# End:
